packages:
  - proxy

shamefullyHoist: true

strictPeerDependencies: false

shellEmulator: true

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  unrs-resolver: false

overrides:
  '@intlify/shared': 9.14.5
  '@intlify/core-base': 9.14.5
  '@intlify/message-compiler': 9.14.5
  vue-i18n: 9.14.5
  '@nuxt/schema': 3.14.1592
  '@nuxt/test-utils': 3.17.0
